let musicList = [
    
    {
        name: "Soch Na Sake",
        artist: "Arijit Singh",
        img: "img/Soch Na Sake.jpg",
        src: "audio/01 - Airlift - Soch Na Sake (Version 1) -DJMaza.Info-.mp3",
        love: false,
    },
    {
        name: "Bas Ek Baar - Fever",
        artist: "Arijit Singh",
        img: "img/Bas Ek Baar - Fever (Arijit Singh).jpg",
        src: "audio/01 - Bas Ek Baar - Fever -DJMaza.Link-.mp3",
        love: false,
    },
    {
        name: "Dilwale - Gerua",
        artist: "Arijit Singh",
        img: "img/Dilwale - Gerua.jpg",
        src: "audio/01 - Dilwale - Gerua -DJMaza.Info-.mp3",
        love: false,
    },
    {
        name: "Hamari Adhuri Kahani",
        artist: "Arijit Singh",
        img: "img/Hamari Adhuri Kahani.jpg",
        src: "audio/01 - HAK - Hamari Adhuri Kahani -DJMaza.Info-.mp3",
        love: false,
    },
    {
        name: "Aaj Dil Shayarana",
        artist: "Arijit Singh",
        img: "img/Aaj Dil Shayarana.jpg",
        src: "audio/01 - Holiday - Aaj Dil Shayarana -MP3khan.Net-.mp3",
        love: false,
    },
    {
        name: "Ishqedarriyaan - Judaa",
        artist: "Arijit Singh",
        img: "img/judaa-arijit-singh.jpg",
        src: "audio/01 - Ishqedarriyaan - Judaa  DJMaza.Info .mp3",
        love: false,
    },
    {
        name: "Kabhi Jo Baadal Barse",
        artist: "Arijit Singh",
        img: "img/Kabhi Jo Baadal Barse.jpg",
        src: "audio/01 - Jackpot - Kabhi Jo Baadal Barse.mp3",
        love: false,
    },
    {
        name: "Khamoshiyan",
        artist: "Arijit Singh",
        img: "img/Khamoshiyan - Khamoshiyan.webp",
        src: "audio/01 - Khamoshiyan - Khamoshiyan  DJMaza.Info .mp3",
        love: false,
    },
    {
        name: "Kuch Parbat Hilaayein",
        artist: "Arijit Singh",
        img: "img/Kuch Parbat Hilaayein.jpg",
        src: "audio/01 - Kuch Parbat Hilaayein  DJMaza.Life .mp3",
        love: false,
    },
    {
        name: "Lo Maan Liya - Raaz Reboot",
        artist: "Arijit Singh",
        img: "img/Lo Maan Liya - Raaz Reboot.jpg",
        src: "audio/01 - Lo Maan Liya - Raaz Reboot -DJMaza.Cool-.mp3",
        love: false,
    },
     {
        name: "Mohenjo Mohenjo",
        artist: "Arijit Singh",
        img: "img/Mohenjo Mohenjo.jpg",
        src: "audio/01 - Mohenjo Mohenjo - Mohenjo Mohenjo  DJMaza.Desi .mp3",
        love: false,
    },
    {
        name: "MTV Unplugged - Arjit Singh",
        artist: "Arijit Singh",
        img: "img/MTV Unplugged - Arjit Singh - Dua.jpg",
        src: "audio/01 - MTV Unplugged - Arjit Singh - Dua -DJMaza-.mp3",
        love: false,
    },
    {
        name: "Salamat - Sarbjit",
        artist: "Arijit Singh",
        img: "img/maxresdefault.jpg",
        src: "audio/01 - Salamat - Sarbjit -DJMaza.Link-.mp3",
        love: false,
    },
    {
        name: " Sanam Re - Sanam Re",
        artist: "Arijit Singh",
        img: "img/Sanam Re (Title Song) Arijit Singh.jpg",
        src: "audio/01 - Sanam Re - Sanam Re -DJMaza.Info-.mp3",
        love: false,
    },
    {
        name: "Sun Le Zara",
        artist: "Arijit Singh",
        img: "img/Sun Le Zara.jpg",
        src: "audio/01 - SR - Sun Le Zara -DJMaza.Info-.mp3",
        love: false,
    },
    {
        name: "Tum Hi Ho - Arijit Singh",
        artist: "Arijit Singh",
        img: "img/Tum Hi Ho - Arijit Singh.jpg",
        src: "audio/01 - Tum Hi Ho - Arijit Singh -DJMaza.Life-.mp3",
        love: false,
    },
    {
        name: "Bas Ek Baar - Fever (Arijit Singh)",
        artist: "Arijit Singh",
        img: "img/Bas Ek Baar - Fever (Arijit Singh).jpg",
        src: "audio/01 Bas Ek Baar - Fever (Arijit Singh) 320Kbps.mp3",
        love: false,
    },
    {
        name: "Manwa Behrupiya - Bollywood Diaries (Arijit Singh)",
        artist: "Arijit Singh",
        img: "img/Manwa Behrupiya - Bollywood Diaries (Arijit Singh).jpg",
        src: "audio/01 Manwa Behrupiya - Bollywood Diaries (Arijit Singh) 320Kbps.mp3",
        love: false,
    },
    {
        name: "Oh Jaaniya (Wedding Pullav)",
        artist: "Arijit Singh",
        img: "img/Oh Jaaniya (Wedding Pullav) Shreya Ghoshal.jpg",
        src: "audio/01 Oh Jaaniya (Wedding Pullav) Shreya Ghoshal 190Kbps.mp3",
        love: false,
    },
    {
        name: "Sanam Re (Title Song) Arijit Singh",
        artist: "Arijit Singh",
        img: "img/Sanam-Re.jpg",
        src: "audio/01 Sanam Re (Title Song) Arijit Singh 320Kbps.mp3",
        love: false,
    },
    {
        name: "Yeh Fitoor Mera - Fitoor (Arijit Singh)",
        artist: "Arijit Singh",
        img: "img/Yeh Fitoor Mera - Fitoor (Arijit Singh).jpg",
        src: "audio/01 Yeh Fitoor Mera - Fitoor (Arijit Singh) 320Kbps.mp3",
        love: false,
    },
    {
        name: "Egiye De",
        artist: "Arijit Singh",
        img: "img/Egiye De.jpg",
        src: "audio/01. Egiye De - -MusicJagat.Com-.mp3",
        love: false,
    },
    {
        name: "Ei Bhalo Ei Kharap (Duet)",
        artist: "Arijit Singh",
        img: "img/Ei Bhalo Ei Kharap (Duet).jpg",
        src: "audio/01. Ei Bhalo Ei Kharap (Duet) - -MusicJagat.Com-.mp3",
        love: false,
    },
    {
        name: "Ghar Aaja Master",
        artist: "Arijit Singh",
        img: "img/Ghar Aaja Master.jpg",
        src: "audio/01. Ghar Aaja Master - -MusicJagat.Com-.mp3",
        love: false,
    },
    {
        name: "Tum Hi Ho",
        artist: "Arijit Singh",
        img: "img/Tum Hi Ho---CooL GuY.jpg",
        src: "audio/01.Tum Hi Ho---CooL GuY- {{a2zRG}}.mp3",
        love: false,
    },
    {
        name: "Ae Dil Hai Mushkil - Arijit Singh",
        artist: "Arijit Singh",
        img: "img/Ae Dil Hai Mushkil - Arijit Singh.jpg",
        src: "audio/02 - Ae Dil Hai Mushkil - Arijit Singh -DJMaza.Life-.mp3",
        love: false,
    },
    {
        name: "Ae Dil Hai Mushkil - Arijit Singh",
        artist: "Arijit Singh",
        img: "img/Ae Dil Hai Mushkil - Arijit Singh.jpg",
        src: "audio/02 - Airlift - Dil Cheez Tujhe Dedi -DJMaza.Info-.mp3",
        love: false,
    },
];
